2024-09-14 18:33:31,407 : INFO : root : Loading config.
2024-09-14 18:33:31,410 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-14 18:33:31,410 : WARNING : ConfigProcessor : Config file in cache changed: /home/pinball/Documents/robowar/config/config.yaml
2024-09-14 18:33:31,410 : INFO : ConfigProcessor : Loading config from file /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml.
2024-09-14 18:33:31,425 : INFO : ConfigProcessor : Loading config: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml
2024-09-14 18:33:31,425 : INFO : ConfigProcessor : Loading config from file /home/pinball/Documents/robowar/config/config.yaml.
2024-09-14 18:33:31,426 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/robowar/config/config.yaml
2024-09-14 18:33:31,426 : INFO : ConfigProcessor : Config file cache created: /tmp/228763e525bfce5a238e0b1bd6dd6347.mpf_cache
2024-09-14 18:33:31,461 : INFO : ConfigProcessor : Loading config from cache: /tmp/8973a6dc4f28e221c9999ded5d94a924.mpf_cache
2024-09-14 18:33:31,461 : INFO : ConfigProcessor : Loading config from cache: /tmp/630a60b96e3d9b5031cbb1e5fa5514c1.mpf_cache
2024-09-14 18:33:31,462 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-14 18:33:31,462 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-09-14-18-33-31-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': '/home/pinball/Documents/robowar/logs/2024-09-14-18-33-31-mpf-mpf.log'}
2024-09-14 18:33:31,462 : INFO : Machine : MPF path: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf
2024-09-14 18:33:31,462 : INFO : Machine : Machine path: /home/pinball/Documents/robowar
2024-09-14 18:33:31,462 : INFO : Machine : Platform: linux
2024-09-14 18:33:31,462 : INFO : Machine : Python executable location: /home/pinball/mpfenv/bin/python3
2024-09-14 18:33:31,462 : INFO : Machine : Python version: 3.12.3 (64-bit)
2024-09-14 18:33:31,464 : INFO : Machine : Initializing MPF...
2024-09-14 18:33:31,525 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-14 18:33:31,526 : INFO : Machine : Shutting down...
2024-09-14 18:33:31,527 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-14 18:33:31,628 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 675, in initialize_mpf
    raise init.exception()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 243, in initialize_core_and_hardware
    await self._initialize_platforms()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 333, in _initialize_platforms
    result.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/platforms/lisy/lisy.py", line 387, in initialize
    self._disable_dts_on_start_of_serial()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/platforms/lisy/lisy.py", line 356, in _disable_dts_on_start_of_serial
    with open(self.config['port']) as serial_port:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'
2024-09-14 18:33:31,632 : INFO : root : MPF run loop ended.
